### ISSUE TITLE
Images fail to load in Firefox

### ISSUE THREAD

**Issue by clarfonthey** [deniszholob/factorio-cheat-sheet#200]
Looks like it might be a CORS issue. Honestly, I think that moving all the images into the repo instead of hotlinking the wiki is a good idea.

**Comment by HonkingGoose** [comment]
Hi @clarfon, I wanted to check if this is still not working for you?
I cannot reproduce your issue on my end.

I'm using Firefox on Windows 10, and I think I see all the relevant pictures when I visit https://factoriocheatsheet.com/

I'm also not getting any warnings about mixed content from Firefox.
https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

Also my Firefox Web Console displays no errors with regards to mixed content.

**Comment by deniszholob** [comment]
I cannot see this either, I use both FF and Chrome regularly, might have been a one time thing or specific to you. I know sometimes various extensions can mess with website presentation in general.

**Comment by ncdulo** [comment]
I came here to mention I was having the images fail to load in Firefox. Reading the last comment about extensions got me looking around. In my case, turns out Privacy Badger was not sure how to handle the `wiki.factorio.com` domain. Setting this to always allowed resolved the issue and allowed images to display on the cheatsheet properly. Figure mentioning the fix here is not a bad idea, may help other users with the same/similar issues in the future.
