### ISSUE TITLE
[Suggestion] Make the menu stay open/static after you click a link item

### ISSUE THREAD

**Issue by ryanmortier** [deniszholob/factorio-cheat-sheet#202]
When ever you click one of these link items, the menu closes. It would be nice to have the option of keeping it open.

![image](https://user-images.githubusercontent.com/2053960/71273962-02bca880-2322-11ea-8d74-ce4f02b78658.png)

**Comment by deniszholob** [comment]
I specifically made it close, b/c why would you want it open after navigating to the data that you need and having it be in the way of you reading?
Its not there for one to just click through and browse, thats what the scrollwheel + collapse function is for.
General use case is open menu click on link and read data not click link again.

However im thinking maybe with larger view ports i can leave it open all the time since it will not obstruct anything
