### ISSUE TITLE
Support for Krastorio 2 (and other mods)

### ISSUE THREAD

**Issue by noerremark** [deniszholob/factorio-cheat-sheet#235]
I would like this to support Krastorio 2 too. It's a big thing to do, and first of all permission to even do it should be obtained.
There is a lot of shared info, lots of shared dynamics (like belt capacity, power, etc.) but also a lot of additional stuff.

My initial idea would be enabling mods-support in a format like this: factoriocheatsheet.com/mods/krastorio2 This would render a Cheat Sheet entirely valid for Krastorio 2.

factoriocheatsheet.com/mods/ would list the (other?) mods supported for indexing by search engines.

**Comment by deniszholob** [comment]
Couple things:
While I don't think i would be opposed to including mod support necessarily, as you said, its a big thing to do, and i do not have the time nor the in depth knowledge of those kinds of game changing mods (I play vanilla most, and only have dabbled in other mods besides ones for QOL) to invest into this, esp as this is a mostly on the side project for fun.
Also, being a project for fun its hosted here on github pages, which from i couldn't make support links like "factoriocheatsheet.com/**/** etc.." when i tried early on in the project, but this could be tested again.

**Comment by deniszholob** [comment]
Support for mods is now live
Just need info to populate new cheat sheets
@noerremark let me know if after this long you are still interested in getting krastorio (or other mods) data in

**Comment by deniszholob** [comment]
Since there where no contributions for mods (understandably so, since a lot of factory planner mods exist anyways)
I decided to remove the mod stuff from production (still exists in the codebase however) because of weirdness with how github pages/routing/custom domain name was killing google crawlers bots. Meaning having it up didnt provide much benefit having a major drawback. Closing for now, may reopen in the future if really needs arise again
