### ISSUE TITLE
Add "How many miners are needed per furnace?" to the mining section

### ISSUE THREAD

**Issue by chases2** [deniszholob/factorio-cheat-sheet#291]
A table similar to the one [here](http://referencio.info/) under "Smelting" would be useful for this reference sheet under mining.

I find that it's useful to just have the ratio of smelters I need for the X miners that I've set up somewhere, without having to convert to "full belts" and back.

**Comment by chases2** [comment]
If there's community support for this, I'd like to try submitting a PR for this as well.

**Comment by deniszholob** [comment]
Not sure if this is really that beneficial to have esp with miners getting global productivity, and that they run out...

When starting out its burner city land so its a 1:1 ratio of burner to furnace so thats EZ to keep track of then with electrics its just 2 furnaces to each miner so also pretty easy to keep track of.
Soon after automation gets researched, it really does become belt based since tillable smelteries are constructed with max a belt can provide, so then the focus is on filling a belt with ore. I don't see a situation were you need to adjust the smelting to the amount of miners, its always the other way around; having enough miners for all the furnaces in the smeltery arrays which are based on max belts...

So the only thing i see that's really useful is listing a base ratio of 1 burner to 1 lvl1 furnace and 1electric to 1 lvl2 or lvl3 furnace maybe
