### ISSUE TITLE
Solar Panel to Accumulator Ratio is wrong

### ISSUE THREAD

**Issue by dBHI-zz** [deniszholob/factorio-cheat-sheet#321]
Hello,

the ratio from solar panels to accumulators is wrong.

A day consists of 4 phases
complete bright: 12500 ticks
complete dark: 2500 ticks
transition: 2 times 5000 ticks with linear rise/descend

because the transition is linear the light gained for solarpanels can be halfed in average, therefore the total lengths are:

bright: 12500 + (5000 / 2) + (5000 /2) = 17500
dark: 2500 + (5000 / 2) + (5000 /2) = 7500

A solarpanel is producing 60 Joul per second for 17500 ticks a day. With 60 ticks per second one solar panel creates 17500 joul a day.

Multiplied by the ratio (dark time / complete day time), which is exactly 0.3, 30% of the 17500 Joul created by a solar panel need to be used during night.  This is 5250 Joul or 5.25 MJ. 

One Accumulator can store 5 MJ, therefor 1.05 Accumulators are needed to store the portion from one solar panel for the night.

This results in a ratio of 1.05 of Accumulators to Solar Panels, or 21 Accumulators to 20 Solar Panels.

Best regards,
Marc

**Comment by dBHI-zz** [comment]
Here is the Maths in Wolframalpha: [Link](https://www.wolframalpha.com/input/?i=%2812500+%2B+%285000+%2F+2%29+%2B+%285000+%2F2%29%29+%2F60*60*%282500+%2B+%285000+%2F+2%29+%2B+%285000+%2F2%29%29%2F25000%2F5000)

**Comment by SpencasaurusRex** [comment]
While I can't speak to what in particular is wrong with your calculations, I did run a quick test in the game version 1.1.39

Test 1:
    Assuming 1.05 accumulator to solar panel ratio
    20 solar panels
    21 accumulators

20 solar panels provide 60kW * 20 = 1.2MW
If we apply that over the average power level of a solar panel at 70% that means that the solar panels should provide us with 1.2MW * 0.7 = 840kW, assuming that the accumulators are smoothing over the gaps for us properly.

I set up a network with precisely 840kW demand via 4 electric furnaces always running (186kW each), and 290 inserters idling (400W each). 
186kW * 4 + 290 * 400W = 860kW
I set it up so that the inserters putting into and pulling out of the furnaces were part of a different network so they aren't counted

I started the test by making sure the accumulators were fully charged during mid-day by connecting a large power source to the network, and disconnecting once fully charged.
Night 1: Accumulators went down to about 18MJ/105MJ at their lowest point
Day 2: Accumulators charged up to 96.5 MJ / 105 MJ
Night 2: Accumulators went down to about 9.5MJ at their lowest point
...
I stopped recording as the trend became clear. Over time the accumulators were not able to completely hold throughout the night, and there was a small satisfaction drop in the network as the solar panels warmed back up in the morning were not able to hold the load.

Test 2
    Assuming 0.84 accumulator to solar panel ratio
    25 solar panels
    21 accumulators

25 solar panels provide 60kW * 25 = 1.5MW
Multiplied by solar panel average
1.5MW * 0.7 = 1.05MW

Network setup with 5 electric furnaces always running (400W each), and 300 inserters idling
186kW * 5 + 300 * 400W = 1.05MW

Again, I ran the test by charging the accumulators fully at noon, before making the network independent.
The network performed perfectly, the accumulators grazed 0 in the morning right before charging back up again, night after night, there was never a satisfaction issue.

**Conclusion**
The existing ratio of 0.84 accumulators to 1 solar panel is correct and should remain in place.

**Comment by deniszholob** [comment]
I have linked the Build ratio to the official wiki article as well that calls for 0.84
https://wiki.factorio.com/Power_production#Solar_panels_and_accumulators

**Comment by deniszholob** [comment]
I have linked the Build ratio to the official wiki article as well that calls for 0.84
https://wiki.factorio.com/Power_production#Solar_panels_and_accumulators

Thanks @dBHI-zz for trying to keep us honest, and thanks to @SpencasaurusRex for your verification efforts
Closing this issue
